server:
  port: 8080
spring:
  application:
    name: weather-intelligence
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weatherdb
    username: weatheruser
    password: weatherpass
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

weather:
  api:
    base-url: https://api.openweathermap.org
    key: 57da890b121c43dba683a7c57dcf96a1

security:
  jwt:
    secret: 0123456789012345678901234567890123456789012345678901234567890123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
